//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiet_donhang
    {
        public int madh { get; set; }
        public int masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
