//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangEntities : DbContext
    {
        public BanHangEntities()
            : base("name=BanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<congnghe> congnghe { get; set; }
        public DbSet<chitiet_donhang> chitiet_donhang { get; set; }
        public DbSet<chitiet_hoadon> chitiet_hoadon { get; set; }
        public DbSet<donhang> donhang { get; set; }
        public DbSet<dungluong> dungluong { get; set; }
        public DbSet<hangsanxuat> hangsanxuat { get; set; }
        public DbSet<hoadon> hoadon { get; set; }
        public DbSet<khachhang> khachhang { get; set; }
        public DbSet<loai> loai { get; set; }
        public DbSet<nhacungcap> nhacungcap { get; set; }
        public DbSet<nhanvien> nhanvien { get; set; }
        public DbSet<quangcao> quangcao { get; set; }
        public DbSet<sanpham> sanpham { get; set; }
    }
}
