//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public hoadon()
        {
            this.chitiet_hoadon = new HashSet<chitiet_hoadon>();
        }
    
        public int mahd { get; set; }
        public int makh { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public string tennguoinhan { get; set; }
        public string diachinhan { get; set; }
        public string dienthoainhan { get; set; }
        public Nullable<bool> httt { get; set; }
        public Nullable<bool> htgh { get; set; }
        public int manv { get; set; }
    
        public virtual ICollection<chitiet_hoadon> chitiet_hoadon { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
