//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacungcap
    {
        public nhacungcap()
        {
            this.sanpham = new HashSet<sanpham>();
        }
    
        public int mancc { get; set; }
        public string tenncc { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<sanpham> sanpham { get; set; }
    }
}
