//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public sanpham()
        {
            this.chitiet_donhang = new HashSet<chitiet_donhang>();
            this.chitiet_hoadon = new HashSet<chitiet_hoadon>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public string hinhsp { get; set; }
        public string mota { get; set; }
        public string kichco { get; set; }
        public string donvitinh { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public int maloai { get; set; }
        public Nullable<int> macn { get; set; }
        public Nullable<int> madl { get; set; }
        public int mancc { get; set; }
        public int mahsx { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> solanxem { get; set; }
    
        public virtual congnghe congnghe { get; set; }
        public virtual ICollection<chitiet_donhang> chitiet_donhang { get; set; }
        public virtual ICollection<chitiet_hoadon> chitiet_hoadon { get; set; }
        public virtual dungluong dungluong { get; set; }
        public virtual hangsanxuat hangsanxuat { get; set; }
        public virtual loai loai { get; set; }
        public virtual nhacungcap nhacungcap { get; set; }
    }
}
